#Docker 1 som alle andre arver fra;
FROM httpd:alpine
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
#COPY ./cgi.sh /usr/local/apache2/cgi-bin/cgi.sh



EXPOSE 80

#Enable CGI support, kan være verdt å endre på?
#ENV HTTP_ENABLE_CGI=true


