CREATE TABLE Bruker (epost VARCHAR(128) PRIMARY KEY NOT NULL UNIQUE, passordhash VARCHAR(4096) NOT NULL, fornavn VARCHAR(64) NOT NULL, etternavn VARCHAR(64) NOT NULL);

CREATE TABLE Sesjon (sesjonsID VARCHAR(128) PRIMARY KEY NOT NULL UNIQUE, epost VARCHAR(128) NOT NULL, FOREIGN KEY(epost) REFERENCES Bruker(epost));

CREATE TABLE Dikt (diktID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, dikt VARCHAR(4096) NOT NULL, epost VARCHAR(128) NOT NULL, FOREIGN KEY(epost) REFERENCES Bruker(epost));